# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cohortwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cohort_settings(object):
    def setupUi(self, cohort_settings):
        cohort_settings.setObjectName("cohort_settings")
        cohort_settings.resize(492, 408)
        self.verticalLayoutWidget = QtWidgets.QWidget(cohort_settings)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 449, 376))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 2)
        self.query_box = QtWidgets.QListView(self.verticalLayoutWidget)
        self.query_box.setObjectName("query_box")
        self.gridLayout.addWidget(self.query_box, 8, 0, 1, 2)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 2, 0, 1, 1)
        self.back = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.back.setObjectName("back")
        self.gridLayout.addWidget(self.back, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.and = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.and.setObjectName("and")
        self.gridLayout.addWidget(self.and, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.or = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.or.setObjectName("or")
        self.gridLayout.addWidget(self.or, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reset = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.reset.setObjectName("reset")
        self.horizontalLayout.addWidget(self.reset)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.save = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.save.setObjectName("save")
        self.horizontalLayout.addWidget(self.save)
        self.cancel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(cohort_settings)
        QtCore.QMetaObject.connectSlotsByName(cohort_settings)

    def retranslateUi(self, cohort_settings):
        _translate = QtCore.QCoreApplication.translate
        cohort_settings.setWindowTitle(_translate("cohort_settings", "Dialog"))
        self.label_4.setText(_translate("cohort_settings", "Creat subcategories"))
        self.back.setText(_translate("cohort_settings", "back"))
        self.label.setText(_translate("cohort_settings", "Categories"))
        self.label_3.setText(_translate("cohort_settings", "Querybox"))
        self.and.setText(_translate("cohort_settings", "and"))
        self.or.setText(_translate("cohort_settings", "or"))
        self.reset.setText(_translate("cohort_settings", "Reset"))
        self.save.setText(_translate("cohort_settings", "Save"))
        self.cancel.setText(_translate("cohort_settings", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cohort_settings = QtWidgets.QDialog()
    ui = Ui_cohort_settings()
    ui.setupUi(cohort_settings)
    cohort_settings.show()
    sys.exit(app.exec_())
