# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_gui_histo_main(object):
    def setupUi(self, gui_histo_main):
        gui_histo_main.setObjectName("gui_histo_main")
        gui_histo_main.resize(916, 701)
        gui_histo_main.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(gui_histo_main)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.Tabs.setEnabled(True)
        font = QtGui.QFont()
        font.setKerning(False)
        self.Tabs.setFont(font)
        self.Tabs.setToolTip("")
        self.Tabs.setIconSize(QtCore.QSize(16, 16))
        self.Tabs.setTabBarAutoHide(False)
        self.Tabs.setObjectName("Tabs")
        self.Deeplearn = QtWidgets.QWidget()
        self.Deeplearn.setAccessibleName("")
        self.Deeplearn.setAutoFillBackground(False)
        self.Deeplearn.setObjectName("Deeplearn")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Deeplearn)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.Deeplearn)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.Deeplearn)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 6, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.Deeplearn)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 11, 7, 1, 1)
        self.validratio_learn = QtWidgets.QSpinBox(self.Deeplearn)
        self.validratio_learn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.validratio_learn.setMaximum(100)
        self.validratio_learn.setProperty("value", 20)
        self.validratio_learn.setObjectName("validratio_learn")
        self.gridLayout.addWidget(self.validratio_learn, 6, 7, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.Deeplearn)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 14, 0, 1, 1)
        self.reset_learn = QtWidgets.QPushButton(self.Deeplearn)
        self.reset_learn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reset_learn.setObjectName("reset_learn")
        self.gridLayout.addWidget(self.reset_learn, 25, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.Deeplearn)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 9, 0, 2, 8)
        self.checkTarget_learn = QtWidgets.QCheckBox(self.Deeplearn)
        self.checkTarget_learn.setText("")
        self.checkTarget_learn.setObjectName("checkTarget_learn")
        self.gridLayout.addWidget(self.checkTarget_learn, 20, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.Deeplearn)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 11, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 13, 6, 1, 1)
        self.savingpath_learn = QtWidgets.QPushButton(self.Deeplearn)
        self.savingpath_learn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.savingpath_learn.setStatusTip("")
        self.savingpath_learn.setObjectName("savingpath_learn")
        self.gridLayout.addWidget(self.savingpath_learn, 1, 1, 1, 1)
        self.choosetarg_learn = QtWidgets.QListWidget(self.Deeplearn)
        self.choosetarg_learn.setEnabled(False)
        self.choosetarg_learn.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.choosetarg_learn.setObjectName("choosetarg_learn")
        self.gridLayout.addWidget(self.choosetarg_learn, 19, 0, 3, 2)
        self.label_3 = QtWidgets.QLabel(self.Deeplearn)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.advanced_sets_learn = QtWidgets.QPushButton(self.Deeplearn)
        self.advanced_sets_learn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.advanced_sets_learn.setObjectName("advanced_sets_learn")
        self.gridLayout.addWidget(self.advanced_sets_learn, 25, 7, 1, 1)
        self.kfolds_learn = QtWidgets.QSpinBox(self.Deeplearn)
        self.kfolds_learn.setEnabled(False)
        self.kfolds_learn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.kfolds_learn.setProperty("value", 3)
        self.kfolds_learn.setObjectName("kfolds_learn")
        self.gridLayout.addWidget(self.kfolds_learn, 8, 7, 1, 1)
        self.choosemode_learn = QtWidgets.QComboBox(self.Deeplearn)
        self.choosemode_learn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.choosemode_learn.setObjectName("choosemode_learn")
        self.choosemode_learn.addItem("")
        self.choosemode_learn.addItem("")
        self.gridLayout.addWidget(self.choosemode_learn, 6, 1, 1, 1)
        self.run_learn = QtWidgets.QPushButton(self.Deeplearn)
        self.run_learn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.run_learn.setObjectName("run_learn")
        self.gridLayout.addWidget(self.run_learn, 25, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.Deeplearn)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.Deeplearn)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 4, 0, 1, 8)
        self.label_settings = QtWidgets.QLabel(self.Deeplearn)
        self.label_settings.setObjectName("label_settings")
        self.gridLayout.addWidget(self.label_settings, 0, 0, 1, 1)
        self.slide_masttab_learn = QtWidgets.QPushButton(self.Deeplearn)
        self.slide_masttab_learn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.slide_masttab_learn.setObjectName("slide_masttab_learn")
        self.gridLayout.addWidget(self.slide_masttab_learn, 12, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.Deeplearn)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 12, 0, 1, 1)
        self.cohortlist_learn = QtWidgets.QListWidget(self.Deeplearn)
        self.cohortlist_learn.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.cohortlist_learn.setObjectName("cohortlist_learn")
        self.gridLayout.addWidget(self.cohortlist_learn, 12, 7, 3, 1)
        self.label_19 = QtWidgets.QLabel(self.Deeplearn)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 18, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.Deeplearn)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 17, 0, 1, 8)
        self.label_9 = QtWidgets.QLabel(self.Deeplearn)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 13, 0, 1, 1)
        self.clini_table_learn = QtWidgets.QPushButton(self.Deeplearn)
        self.clini_table_learn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clini_table_learn.setObjectName("clini_table_learn")
        self.gridLayout.addWidget(self.clini_table_learn, 13, 1, 1, 1)
        self.tilespath_learn = QtWidgets.QPushButton(self.Deeplearn)
        self.tilespath_learn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tilespath_learn.setObjectName("tilespath_learn")
        self.gridLayout.addWidget(self.tilespath_learn, 14, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.Deeplearn)
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 8, 0, 1, 1)
        self.checkSubset_learn = QtWidgets.QCheckBox(self.Deeplearn)
        self.checkSubset_learn.setText("")
        self.checkSubset_learn.setObjectName("checkSubset_learn")
        self.gridLayout.addWidget(self.checkSubset_learn, 19, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.Deeplearn)
        self.label_5.setEnabled(False)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 6, 1, 1)
        self.test_learn = QtWidgets.QPushButton(self.Deeplearn)
        self.test_learn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.test_learn.setObjectName("test_learn")
        self.gridLayout.addWidget(self.test_learn, 23, 7, 1, 1)
        self.train_subset_learn = QtWidgets.QPushButton(self.Deeplearn)
        self.train_subset_learn.setEnabled(False)
        self.train_subset_learn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.train_subset_learn.setObjectName("train_subset_learn")
        self.gridLayout.addWidget(self.train_subset_learn, 19, 3, 1, 1)
        self.add_target_learn = QtWidgets.QPushButton(self.Deeplearn)
        self.add_target_learn.setEnabled(False)
        self.add_target_learn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_target_learn.setObjectName("add_target_learn")
        self.gridLayout.addWidget(self.add_target_learn, 20, 3, 1, 1)
        self.addcohortlist_learn = QtWidgets.QPushButton(self.Deeplearn)
        self.addcohortlist_learn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/right-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addcohortlist_learn.setIcon(icon)
        self.addcohortlist_learn.setObjectName("addcohortlist_learn")
        self.gridLayout.addWidget(self.addcohortlist_learn, 13, 3, 1, 1)
        self.del_list_learn = QtWidgets.QPushButton(self.Deeplearn)
        self.del_list_learn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.del_list_learn.setIcon(icon1)
        self.del_list_learn.setIconSize(QtCore.QSize(13, 13))
        self.del_list_learn.setObjectName("del_list_learn")
        self.gridLayout.addWidget(self.del_list_learn, 14, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.Tabs.addTab(self.Deeplearn, "")
        self.Deploy = QtWidgets.QWidget()
        self.Deploy.setObjectName("Deploy")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Deploy)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.test_deploy = QtWidgets.QPushButton(self.Deploy)
        self.test_deploy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.test_deploy.setObjectName("test_deploy")
        self.gridLayout_2.addWidget(self.test_deploy, 19, 7, 1, 1)
        self.run_deploy = QtWidgets.QPushButton(self.Deploy)
        self.run_deploy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.run_deploy.setObjectName("run_deploy")
        self.gridLayout_2.addWidget(self.run_deploy, 20, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.Deploy)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 10, 0, 1, 1)
        self.choose_tiledir_deploy = QtWidgets.QPushButton(self.Deploy)
        self.choose_tiledir_deploy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.choose_tiledir_deploy.setObjectName("choose_tiledir_deploy")
        self.gridLayout_2.addWidget(self.choose_tiledir_deploy, 12, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.Deploy)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 14, 0, 1, 1)
        self.add_eval_deploy = QtWidgets.QPushButton(self.Deploy)
        self.add_eval_deploy.setIcon(icon)
        self.add_eval_deploy.setObjectName("add_eval_deploy")
        self.gridLayout_2.addWidget(self.add_eval_deploy, 16, 4, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.Deploy)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.Deploy)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 7, 1, 1)
        self.del_list_deploy = QtWidgets.QPushButton(self.Deploy)
        self.del_list_deploy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.del_list_deploy.setIcon(icon1)
        self.del_list_deploy.setIconSize(QtCore.QSize(13, 13))
        self.del_list_deploy.setObjectName("del_list_deploy")
        self.gridLayout_2.addWidget(self.del_list_deploy, 12, 4, 1, 1)
        self.savingpath_deploy = QtWidgets.QPushButton(self.Deploy)
        self.savingpath_deploy.setObjectName("savingpath_deploy")
        self.gridLayout_2.addWidget(self.savingpath_deploy, 3, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.Deploy)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 12, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.Deploy)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.addlist_deploy = QtWidgets.QPushButton(self.Deploy)
        self.addlist_deploy.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addlist_deploy.sizePolicy().hasHeightForWidth())
        self.addlist_deploy.setSizePolicy(sizePolicy)
        self.addlist_deploy.setMinimumSize(QtCore.QSize(0, 32))
        self.addlist_deploy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addlist_deploy.setStyleSheet("")
        self.addlist_deploy.setIcon(icon)
        self.addlist_deploy.setObjectName("addlist_deploy")
        self.gridLayout_2.addWidget(self.addlist_deploy, 11, 4, 1, 1)
        self.projectdir_deploy = QtWidgets.QPushButton(self.Deploy)
        self.projectdir_deploy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.projectdir_deploy.setObjectName("projectdir_deploy")
        self.gridLayout_2.addWidget(self.projectdir_deploy, 1, 2, 1, 1)
        self.reset_deploy = QtWidgets.QPushButton(self.Deploy)
        self.reset_deploy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reset_deploy.setObjectName("reset_deploy")
        self.gridLayout_2.addWidget(self.reset_deploy, 20, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 8, 6, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.Deploy)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 3, 0, 1, 1)
        self.cohortlist_deploy = QtWidgets.QListWidget(self.Deploy)
        self.cohortlist_deploy.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.cohortlist_deploy.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.cohortlist_deploy.setObjectName("cohortlist_deploy")
        self.gridLayout_2.addWidget(self.cohortlist_deploy, 10, 7, 3, 1)
        self.check_Subset_deploy = QtWidgets.QCheckBox(self.Deploy)
        self.check_Subset_deploy.setText("")
        self.check_Subset_deploy.setObjectName("check_Subset_deploy")
        self.gridLayout_2.addWidget(self.check_Subset_deploy, 19, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.Deploy)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 11, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.Deploy)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 8, 7, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.Deploy)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 3, 1, 1)
        self.advanced_deploy = QtWidgets.QPushButton(self.Deploy)
        self.advanced_deploy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.advanced_deploy.setObjectName("advanced_deploy")
        self.gridLayout_2.addWidget(self.advanced_deploy, 20, 7, 1, 1)
        self.choose_slidetable_deploy = QtWidgets.QPushButton(self.Deploy)
        self.choose_slidetable_deploy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.choose_slidetable_deploy.setObjectName("choose_slidetable_deploy")
        self.gridLayout_2.addWidget(self.choose_slidetable_deploy, 10, 2, 1, 1)
        self.choose_model_deploy = QtWidgets.QPushButton(self.Deploy)
        self.choose_model_deploy.setEnabled(False)
        self.choose_model_deploy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.choose_model_deploy.setObjectName("choose_model_deploy")
        self.gridLayout_2.addWidget(self.choose_model_deploy, 2, 2, 1, 1)
        self.del_eval_list_deploy = QtWidgets.QPushButton(self.Deploy)
        self.del_eval_list_deploy.setIcon(icon1)
        self.del_eval_list_deploy.setIconSize(QtCore.QSize(13, 13))
        self.del_eval_list_deploy.setObjectName("del_eval_list_deploy")
        self.gridLayout_2.addWidget(self.del_eval_list_deploy, 17, 4, 1, 1)
        self.clini_table_deploy = QtWidgets.QPushButton(self.Deploy)
        self.clini_table_deploy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clini_table_deploy.setObjectName("clini_table_deploy")
        self.gridLayout_2.addWidget(self.clini_table_deploy, 11, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.Deploy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.Deploy)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 13, 0, 1, 8)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 8, 3, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.Deploy)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 7, 0, 1, 8)
        self.label_29 = QtWidgets.QLabel(self.Deploy)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 8, 0, 1, 1)
        self.deploy_subset = QtWidgets.QPushButton(self.Deploy)
        self.deploy_subset.setEnabled(False)
        self.deploy_subset.setObjectName("deploy_subset")
        self.gridLayout_2.addWidget(self.deploy_subset, 19, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 4, 4, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.Deploy)
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 4, 2, 1, 1)
        self.targetlabels_deploy = QtWidgets.QListWidget(self.Deploy)
        self.targetlabels_deploy.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.targetlabels_deploy.setObjectName("targetlabels_deploy")
        self.gridLayout_2.addWidget(self.targetlabels_deploy, 1, 7, 4, 1)
        self.label_31 = QtWidgets.QLabel(self.Deploy)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 14, 7, 1, 1)
        self.evaluator_list_deploy = QtWidgets.QListWidget(self.Deploy)
        self.evaluator_list_deploy.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.evaluator_list_deploy.setProperty("showDropIndicator", False)
        self.evaluator_list_deploy.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.evaluator_list_deploy.setObjectName("evaluator_list_deploy")
        self.gridLayout_2.addWidget(self.evaluator_list_deploy, 16, 7, 3, 1)
        self.label_27 = QtWidgets.QLabel(self.Deploy)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 18, 0, 1, 1)
        self.group_evaluators_deploy = QtWidgets.QComboBox(self.Deploy)
        self.group_evaluators_deploy.setObjectName("group_evaluators_deploy")
        self.group_evaluators_deploy.addItem("")
        self.gridLayout_2.addWidget(self.group_evaluators_deploy, 18, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.Deploy)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 17, 0, 1, 1)
        self.evaluators_deploy = QtWidgets.QComboBox(self.Deploy)
        self.evaluators_deploy.setObjectName("evaluators_deploy")
        self.evaluators_deploy.addItem("")
        self.evaluators_deploy.addItem("")
        self.evaluators_deploy.addItem("")
        self.evaluators_deploy.addItem("")
        self.evaluators_deploy.addItem("")
        self.evaluators_deploy.addItem("")
        self.evaluators_deploy.addItem("")
        self.evaluators_deploy.addItem("")
        self.evaluators_deploy.addItem("")
        self.evaluators_deploy.addItem("")
        self.gridLayout_2.addWidget(self.evaluators_deploy, 17, 2, 1, 1)
        self.eval_type_deploy = QtWidgets.QComboBox(self.Deploy)
        self.eval_type_deploy.setObjectName("eval_type_deploy")
        self.eval_type_deploy.addItem("")
        self.eval_type_deploy.addItem("")
        self.eval_type_deploy.addItem("")
        self.gridLayout_2.addWidget(self.eval_type_deploy, 14, 2, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_2)
        self.Tabs.addTab(self.Deploy, "")
        self.Visualize = QtWidgets.QWidget()
        self.Visualize.setObjectName("Visualize")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.Visualize)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 1, 1, 1)
        self.eval_list_vis = QtWidgets.QListWidget(self.Visualize)
        self.eval_list_vis.setObjectName("eval_list_vis")
        self.gridLayout_3.addWidget(self.eval_list_vis, 4, 0, 1, 1)
        self.target_list_vis = QtWidgets.QListWidget(self.Visualize)
        self.target_list_vis.setObjectName("target_list_vis")
        self.gridLayout_3.addWidget(self.target_list_vis, 2, 0, 1, 1)
        self.choose_path_vis = QtWidgets.QPushButton(self.Visualize)
        self.choose_path_vis.setObjectName("choose_path_vis")
        self.gridLayout_3.addWidget(self.choose_path_vis, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.Visualize)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.Visualize)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 3, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.Visualize)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(-1, 9, 561, 511))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.toptiles_graph_vis = QtWidgets.QGraphicsView(self.gridLayoutWidget_3)
        self.toptiles_graph_vis.setObjectName("toptiles_graph_vis")
        self.gridLayout_5.addWidget(self.toptiles_graph_vis, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(-1, 9, 561, 511))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.plots_vis = QtWidgets.QGraphicsView(self.formLayoutWidget)
        self.plots_vis.setObjectName("plots_vis")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.plots_vis)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(-1, 9, 561, 511))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.logs_vis = QtWidgets.QGraphicsView(self.formLayoutWidget_2)
        self.logs_vis.setObjectName("logs_vis")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.logs_vis)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 578, 501))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.listWidget_3 = QtWidgets.QListWidget(self.gridLayoutWidget_2)
        self.listWidget_3.setObjectName("listWidget_3")
        self.gridLayout_4.addWidget(self.listWidget_3, 2, 4, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.gridLayoutWidget_2)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_4.addWidget(self.graphicsView, 2, 0, 1, 4)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 0, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_4.addWidget(self.lcdNumber, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 0, 4, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.pushButton_4, 1, 4, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_5)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(-1, -1, 561, 521))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.foldertree_vis = QtWidgets.QTreeWidget(self.formLayoutWidget_3)
        self.foldertree_vis.setObjectName("foldertree_vis")
        self.foldertree_vis.headerItem().setText(0, "1")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.foldertree_vis)
        self.simple_vis_graph = QtWidgets.QGraphicsView(self.formLayoutWidget_3)
        self.simple_vis_graph.setObjectName("simple_vis_graph")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.simple_vis_graph)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout_3.addWidget(self.tabWidget, 1, 1, 4, 3)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_7.addLayout(self.horizontalLayout)
        self.Tabs.addTab(self.Visualize, "")
        self.horizontalLayout_2.addWidget(self.Tabs)
        gui_histo_main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(gui_histo_main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 916, 24))
        self.menubar.setObjectName("menubar")
        self.menuhello = QtWidgets.QMenu(self.menubar)
        self.menuhello.setObjectName("menuhello")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTutorial = QtWidgets.QMenu(self.menuHelp)
        self.menuTutorial.setObjectName("menuTutorial")
        gui_histo_main.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(gui_histo_main)
        self.toolBar.setObjectName("toolBar")
        gui_histo_main.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionQuit_Deep_Histology = QtWidgets.QAction(gui_histo_main)
        self.actionQuit_Deep_Histology.setObjectName("actionQuit_Deep_Histology")
        self.actionPreferences = QtWidgets.QAction(gui_histo_main)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionNew_Experiment = QtWidgets.QAction(gui_histo_main)
        self.actionNew_Experiment.setObjectName("actionNew_Experiment")
        self.actionOpen_Experiment = QtWidgets.QAction(gui_histo_main)
        self.actionOpen_Experiment.setObjectName("actionOpen_Experiment")
        self.actionMenu = QtWidgets.QAction(gui_histo_main)
        self.actionMenu.setObjectName("actionMenu")
        self.actionGithub_Documentation = QtWidgets.QAction(gui_histo_main)
        self.actionGithub_Documentation.setObjectName("actionGithub_Documentation")
        self.actionarr = QtWidgets.QAction(gui_histo_main)
        self.actionarr.setObjectName("actionarr")
        self.actionDeep_Learn = QtWidgets.QAction(gui_histo_main)
        self.actionDeep_Learn.setObjectName("actionDeep_Learn")
        self.actionDeploy = QtWidgets.QAction(gui_histo_main)
        self.actionDeploy.setObjectName("actionDeploy")
        self.actionVisualize = QtWidgets.QAction(gui_histo_main)
        self.actionVisualize.setObjectName("actionVisualize")
        self.menuhello.addSeparator()
        self.menuhello.addAction(self.actionPreferences)
        self.menuhello.addAction(self.actionQuit_Deep_Histology)
        self.menuFile.addAction(self.actionNew_Experiment)
        self.menuFile.addAction(self.actionOpen_Experiment)
        self.menuEdit.addAction(self.actionMenu)
        self.menuTutorial.addAction(self.actionDeep_Learn)
        self.menuTutorial.addAction(self.actionDeploy)
        self.menuTutorial.addAction(self.actionVisualize)
        self.menuHelp.addAction(self.actionGithub_Documentation)
        self.menuHelp.addAction(self.menuTutorial.menuAction())
        self.menubar.addAction(self.menuhello.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(gui_histo_main)
        self.Tabs.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(gui_histo_main)

    def retranslateUi(self, gui_histo_main):
        _translate = QtCore.QCoreApplication.translate
        gui_histo_main.setWindowTitle(_translate("gui_histo_main", "Deep Histology v2.1"))
        self.label_6.setText(_translate("gui_histo_main", "Mode Settings:"))
        self.label_4.setText(_translate("gui_histo_main", "validation ratio"))
        self.label_28.setText(_translate("gui_histo_main", "cohort list:"))
        self.validratio_learn.setSuffix(_translate("gui_histo_main", "%"))
        self.label_2.setText(_translate("gui_histo_main", "tiles path"))
        self.reset_learn.setText(_translate("gui_histo_main", "reset"))
        self.label_25.setText(_translate("gui_histo_main", "Cohort Settings:"))
        self.savingpath_learn.setText(_translate("gui_histo_main", "choose folder"))
        self.label_3.setText(_translate("gui_histo_main", "mode"))
        self.advanced_sets_learn.setText(_translate("gui_histo_main", "advanced settings"))
        self.choosemode_learn.setItemText(0, _translate("gui_histo_main", "test/train"))
        self.choosemode_learn.setItemText(1, _translate("gui_histo_main", "k-fold cross validation"))
        self.run_learn.setText(_translate("gui_histo_main", "run"))
        self.label_12.setText(_translate("gui_histo_main", "saving path"))
        self.label_settings.setText(_translate("gui_histo_main", "Settings:"))
        self.slide_masttab_learn.setToolTip(_translate("gui_histo_main", "choose a slide table"))
        self.slide_masttab_learn.setText(_translate("gui_histo_main", "choose file"))
        self.label_8.setText(_translate("gui_histo_main", "slide table"))
        self.cohortlist_learn.setSortingEnabled(True)
        self.label_19.setText(_translate("gui_histo_main", "Choose Target(s):"))
        self.label_9.setText(_translate("gui_histo_main", "clini table"))
        self.clini_table_learn.setText(_translate("gui_histo_main", "choose file"))
        self.tilespath_learn.setText(_translate("gui_histo_main", "choose path"))
        self.label_5.setText(_translate("gui_histo_main", "k-folds"))
        self.test_learn.setText(_translate("gui_histo_main", "test"))
        self.train_subset_learn.setText(_translate("gui_histo_main", "train on subset"))
        self.add_target_learn.setText(_translate("gui_histo_main", "add target"))
        self.addcohortlist_learn.setText(_translate("gui_histo_main", "add to list"))
        self.del_list_learn.setText(_translate("gui_histo_main", "delete list"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Deeplearn), _translate("gui_histo_main", "Deep Learn"))
        self.test_deploy.setText(_translate("gui_histo_main", "test"))
        self.run_deploy.setText(_translate("gui_histo_main", "run"))
        self.label_21.setText(_translate("gui_histo_main", "slide table"))
        self.choose_tiledir_deploy.setText(_translate("gui_histo_main", "choose folder"))
        self.label_20.setText(_translate("gui_histo_main", "Evaluators:"))
        self.add_eval_deploy.setText(_translate("gui_histo_main", "add to list"))
        self.label_24.setText(_translate("gui_histo_main", "training project directory"))
        self.label_15.setText(_translate("gui_histo_main", "choose models:"))
        self.del_list_deploy.setText(_translate("gui_histo_main", "delete list"))
        self.savingpath_deploy.setText(_translate("gui_histo_main", "choohe path"))
        self.label_22.setText(_translate("gui_histo_main", "tile directory"))
        self.label_11.setText(_translate("gui_histo_main", "model path"))
        self.addlist_deploy.setText(_translate("gui_histo_main", "add to list"))
        self.projectdir_deploy.setText(_translate("gui_histo_main", "choose folder"))
        self.reset_deploy.setText(_translate("gui_histo_main", "reset"))
        self.label_18.setText(_translate("gui_histo_main", "project directory "))
        self.cohortlist_deploy.setSortingEnabled(True)
        self.label.setText(_translate("gui_histo_main", "clini table"))
        self.label_23.setText(_translate("gui_histo_main", "cohort list:"))
        self.label_10.setText(_translate("gui_histo_main", "   -or-"))
        self.advanced_deploy.setText(_translate("gui_histo_main", "advanced settings"))
        self.choose_slidetable_deploy.setText(_translate("gui_histo_main", "choose file"))
        self.choose_model_deploy.setText(_translate("gui_histo_main", "choose path"))
        self.del_eval_list_deploy.setText(_translate("gui_histo_main", "delete list"))
        self.clini_table_deploy.setText(_translate("gui_histo_main", "choose file"))
        self.label_7.setText(_translate("gui_histo_main", "Settings:"))
        self.label_29.setText(_translate("gui_histo_main", "Cohort settings:"))
        self.deploy_subset.setText(_translate("gui_histo_main", "deploy on subset"))
        self.label_31.setText(_translate("gui_histo_main", "evaluator list:"))
        self.label_27.setText(_translate("gui_histo_main", "group by"))
        self.group_evaluators_deploy.setItemText(0, _translate("gui_histo_main", "no grouping"))
        self.label_26.setText(_translate("gui_histo_main", "Evaluator"))
        self.evaluators_deploy.setItemText(0, _translate("gui_histo_main", "auroc"))
        self.evaluators_deploy.setItemText(1, _translate("gui_histo_main", "count"))
        self.evaluators_deploy.setItemText(2, _translate("gui_histo_main", "p_value"))
        self.evaluators_deploy.setItemText(3, _translate("gui_histo_main", "r2"))
        self.evaluators_deploy.setItemText(4, _translate("gui_histo_main", "AggregateStats"))
        self.evaluators_deploy.setItemText(5, _translate("gui_histo_main", "ConfusionMatrix"))
        self.evaluators_deploy.setItemText(6, _translate("gui_histo_main", "F1"))
        self.evaluators_deploy.setItemText(7, _translate("gui_histo_main", "Heatmap"))
        self.evaluators_deploy.setItemText(8, _translate("gui_histo_main", "Roc"))
        self.evaluators_deploy.setItemText(9, _translate("gui_histo_main", "TopTiles"))
        self.eval_type_deploy.setItemText(0, _translate("gui_histo_main", "single"))
        self.eval_type_deploy.setItemText(1, _translate("gui_histo_main", "multi"))
        self.eval_type_deploy.setItemText(2, _translate("gui_histo_main", "cross_validation"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Deploy), _translate("gui_histo_main", "Deploy"))
        self.choose_path_vis.setText(_translate("gui_histo_main", "choose path"))
        self.label_13.setText(_translate("gui_histo_main", "Evaluators:"))
        self.label_14.setText(_translate("gui_histo_main", "Targets:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("gui_histo_main", "Top Tiles"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("gui_histo_main", "Plots"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("gui_histo_main", "Logs"))
        self.label_17.setText(_translate("gui_histo_main", "Current Image"))
        self.pushButton.setText(_translate("gui_histo_main", "Previous Image"))
        self.pushButton_2.setText(_translate("gui_histo_main", "Open Folder"))
        self.pushButton_4.setText(_translate("gui_histo_main", "List of Images"))
        self.pushButton_3.setText(_translate("gui_histo_main", "Next Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("gui_histo_main", "Tiles"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("gui_histo_main", "simple vis"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Visualize), _translate("gui_histo_main", "Visualize"))
        self.menuhello.setTitle(_translate("gui_histo_main", "Deep Histology"))
        self.menuFile.setTitle(_translate("gui_histo_main", "File"))
        self.menuEdit.setTitle(_translate("gui_histo_main", "Edit"))
        self.menuView.setTitle(_translate("gui_histo_main", "View"))
        self.menuHelp.setTitle(_translate("gui_histo_main", "Help"))
        self.menuTutorial.setTitle(_translate("gui_histo_main", "Tutorial"))
        self.toolBar.setWindowTitle(_translate("gui_histo_main", "toolBar"))
        self.actionQuit_Deep_Histology.setText(_translate("gui_histo_main", "Quit Deep Histology"))
        self.actionPreferences.setText(_translate("gui_histo_main", "Preferences"))
        self.actionNew_Experiment.setText(_translate("gui_histo_main", "New Experiment"))
        self.actionOpen_Experiment.setText(_translate("gui_histo_main", "Open Experiment"))
        self.actionMenu.setText(_translate("gui_histo_main", "Menu"))
        self.actionGithub_Documentation.setText(_translate("gui_histo_main", "Github Documentation"))
        self.actionarr.setText(_translate("gui_histo_main", "arr"))
        self.actionDeep_Learn.setText(_translate("gui_histo_main", "Deep Learn"))
        self.actionDeploy.setText(_translate("gui_histo_main", "Deploy"))
        self.actionVisualize.setText(_translate("gui_histo_main", "Visualize"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gui_histo_main = QtWidgets.QMainWindow()
    ui = Ui_gui_histo_main()
    ui.setupUi(gui_histo_main)
    gui_histo_main.show()
    sys.exit(app.exec_())

